### ISSUE TITLE
`inbox` does not return JS file anymore

### ISSUE THREAD

**Issue by BotBoiii** [scottmconway/unzuckify#2]
`inbox` for me doesn't return a JS anymore.

`esprima.parseScript(inbox_js, delegate=delegate)` breaks with `esprima.error_handler.Error: Line 1: Unexpected token :`.

Is it still working for you?

**Comment by scottmconway** [comment]
I don't use this tool anymore, since I'm interested in getting notifications (and not sending messages) from marketplace messages, which this tool cannot support.

That said, contributions are certainly welcome, and I can spend some time looking into this. Would you be able to provide a full traceback and/or debug-level log?

I do have a better read-only solution for getting messenger notifications that I intend to share shortly. I'll drop a link here when it's ready.

**Comment by joja16** [comment]
> I don't use this tool anymore, since I'm interested in getting notifications (and not sending messages) from marketplace messages, which this tool cannot support.
> 
> That said, contributions are certainly welcome, and I can spend some time looking into this. Would you be able to provide a full traceback and/or debug-level log?
> 
> I do have a better read-only solution for getting messenger notifications that I intend to share shortly. I'll drop a link here when it's ready.

I look forward to your link

**Comment by scottmconway** [comment]
I'm still drafting a blog post on my complete setup, but in short, I recommend installing FB Messenger on an Android device with [Notifikator](https://github.com/koro666/notifikator/) or another notification-forwarding tool.

I have a [fork of Notifikator](https://github.com/scottmconway/notifikator/) that may be worth looking at, since I've added support for logging to Gotify. Be warned that there's a deny list for logging notifications by package name that's currently hard-coded [here](https://github.com/scottmconway/notifikator/blob/master/client/src/main/java/net/kzxiv/notify/client/NotificationService.java#L39).

My blog post is going to go over other potential solutions that could come in the future, but the absolute tl;dr is this:
* FB doesn't want you using their backend APIs
* FB may change their backend APIs suddenly, and without warning
* FB wants notifications to be properly delivered to users of their apps, even through changes to these APIs

Thus, it's safe to receive notifications from facebook if you act like a normal user. I have no interest in having messenger installed on any device that I actually use or store information on, but instead I have a dedicated android device for notification forwarding. It could even be a VM.

I'll post a link to the blog post when I'm happy with it, but there's not much more to add, besides discussion of other possibilities to achieve the same end result, and notes about my exact notification forwarding setup.
